### ISSUE TITLE
Issue when attribute location_id_friendlyname doesn't exist in datamodel

### ISSUE THREAD

**Issue by jnoelhardis** [Molkobain/itop-newsroom-provider#1]
If the attribute location_id_friendlyname doesn't exist in datamodel there is an issue.
![image](https://user-images.githubusercontent.com/75981580/102201391-52e33200-3ec6-11eb-8233-627c3566b5d4.png)

**Comment by Molkobain** [comment]
Fixed in https://github.com/Molkobain/itop-newsroom-provider/commit/8df7f97fefb65712ae32a2bf576332eaa2877ab4
Only the "Bubble caselogs" extension has been updated for now, the others will follow soon.
